project:
  type: website
  output-dir: docs

website:
  title: "Dan Nolte"
  image: photos/headshot.jpg
  navbar:
    background: "#F78734"
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: "Blog"
        href: blog/overview.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.pdf

  sidebar:
    - title: "Blog"
      style: "docked"
      background: light
      contents:
        - blog/overview.qmd
        - blog/sql.qmd
        - blog/python.qmd
        - blog/stats.qmd
        - blog/machine-learning.qmd

    - title: Projects
      contents:
        - projects.qmd

    - title: Resume
      contents:
        - resume.pdf


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

