project:
  type: website
  output-dir: docs

website:
  title: "Dan Nolte"
  image: photos/headshot.jpg
  navbar:
    background: "#F78734"
    search: true
    left:
      - href: index.qmd
        text: Home
      - values.qmd
      - text: "Words"
        menu:
          - statistics.qmd
          - reviews.qmd
          - musings.qmd
      - projects.qmd
      - text: Resume
        href: resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

