---
title: "Values"
format: html
---

When I admire people, they normally do these things.

**Tell the truth:**
They say things that are true, quantifying uncertainty as appropriate. They don't say things that are false. They follow these rules relentlessly, and especially when delivering news people don't want to hear. 

**Use their words:**
They initiate difficult conversations and don't allow important things to go [unsaid](https://www.poemtree.com/poems/Unsaid.htm), especially with those close to them. 

**Write:**
They use writing as a tool to [clarify their thinking](https://paulgraham.com/words.html). (As an aside, I believe writing is highly underrated in the workplace. I endorse the [Amazon approach to meetings](https://www.youtube.com/watch?v=FaXocwfDF-E).)

**Balance their lives:**
They understand that [life is short](https://www.youtube.com/watch?v=ji5_MqicxSo) and we get one chance at this. They design their lives appropriately. 

**Seek new experiences:**
They resist [status quo bias](https://en.wikipedia.org/wiki/Status_quo_bias) and they try new things to make their lives richer. 

**Engage with the world:**
They actively participate in the communities where they live, and they recognize that their choices matter and they have the capacity to change the world. 